// TODO YYYY/MM/DD

const trips = [
  {
    "id": 1,
    "userID": 44,
    "destinationID": 49,
    "travelers": 1,
    "date": "2019/09/16",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  },
  {
    "id": 2,
    "userID": 35,
    "destinationID": 25,
    "travelers": 5,
    "date": "2020/10/04",
    "duration": 18,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 3,
    "userID": 3,
    "destinationID": 22,
    "travelers": 4,
    "date": "2020/05/22",
    "duration": 17,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 4,
    "userID": 43,
    "destinationID": 14,
    "travelers": 2,
    "date": "2020/02/25",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 5,
    "userID": 42,
    "destinationID": 29,
    "travelers": 3,
    "date": "2020/04/30",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 6,
    "userID": 29,
    "destinationID": 35,
    "travelers": 3,
    "date": "2020/06/29",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 7,
    "userID": 37,
    "destinationID": 17,
    "travelers": 5,
    "date": "2020/5/28",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 8,
    "userID": 36,
    "destinationID": 39,
    "travelers": 6,
    "date": "2021/02/07",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 9,
    "userID": 24,
    "destinationID": 19,
    "travelers": 5,
    "date": "2019/12/19",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 10,
    "userID": 9,
    "destinationID": 50,
    "travelers": 6,
    "date": "2020/07/23",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 11,
    "userID": 50,
    "destinationID": 5,
    "travelers": 4,
    "date": "2020/10/14",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 12,
    "userID": 33,
    "destinationID": 33,
    "travelers": 6,
    "date": "2020/10/17",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 13,
    "userID": 14,
    "destinationID": 12,
    "travelers": 1,
    "date": "2021/02/12",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 14,
    "userID": 19,
    "destinationID": 35,
    "travelers": 1,
    "date": "2020/09/24",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 15,
    "userID": 50,
    "destinationID": 13,
    "travelers": 3,
    "date": "2020/07/04",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 16,
    "userID": 19,
    "destinationID": 27,
    "travelers": 1,
    "date": "2019/11/20",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 17,
    "userID": 28,
    "destinationID": 31,
    "travelers": 1,
    "date": "2019/10/30",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 18,
    "userID": 18,
    "destinationID": 2,
    "travelers": 2,
    "date": "2020/09/25",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 19,
    "userID": 47,
    "destinationID": 47,
    "travelers": 4,
    "date": "2019/07/21",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 20,
    "userID": 41,
    "destinationID": 19,
    "travelers": 4,
    "date": "2020/10/05",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 21,
    "userID": 12,
    "destinationID": 10,
    "travelers": 1,
    "date": "2020/01/28",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 22,
    "userID": 22,
    "destinationID": 9,
    "travelers": 4,
    "date": "2020/05/01",
    "duration": 19,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 23,
    "userID": 14,
    "destinationID": 24,
    "travelers": 6,
    "date": "2020/01/02",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 24,
    "userID": 46,
    "destinationID": 26,
    "travelers": 5,
    "date": "2019/11/15",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 25,
    "userID": 18,
    "destinationID": 12,
    "travelers": 6,
    "date": "2019/10/26",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 26,
    "userID": 25,
    "destinationID": 15,
    "travelers": 3,
    "date": "2019/12/10",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 27,
    "userID": 43,
    "destinationID": 7,
    "travelers": 6,
    "date": "2019/07/16",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 28,
    "userID": 48,
    "destinationID": 31,
    "travelers": 3,
    "date": "2020/02/03",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 29,
    "userID": 42,
    "destinationID": 25,
    "travelers": 3,
    "date": "2019/08/30",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 30,
    "userID": 33,
    "destinationID": 29,
    "travelers": 1,
    "date": "2020/07/17",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 31,
    "userID": 11,
    "destinationID": 33,
    "travelers": 3,
    "date": "2020/12/19",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 32,
    "userID": 34,
    "destinationID": 36,
    "travelers": 5,
    "date": "2020/05/06",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 33,
    "userID": 6,
    "destinationID": 36,
    "travelers": 5,
    "date": "2020/03/26",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 34,
    "userID": 32,
    "destinationID": 14,
    "travelers": 5,
    "date": "2019/08/02",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 35,
    "userID": 36,
    "destinationID": 1,
    "travelers": 3,
    "date": "2020/10/23",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 36,
    "userID": 30,
    "destinationID": 26,
    "travelers": 5,
    "date": "2019/10/20",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 37,
    "userID": 49,
    "destinationID": 24,
    "travelers": 2,
    "date": "2021/02/20",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 38,
    "userID": 47,
    "destinationID": 20,
    "travelers": 2,
    "date": "2020/11/16",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 39,
    "userID": 42,
    "destinationID": 25,
    "travelers": 3,
    "date": "2019/10/22",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 40,
    "userID": 29,
    "destinationID": 50,
    "travelers": 3,
    "date": "2020/10/31",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 41,
    "userID": 3,
    "destinationID": 25,
    "travelers": 3,
    "date": "2020/08/30",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 42,
    "userID": 11,
    "destinationID": 32,
    "travelers": 1,
    "date": "2020/08/08",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 43,
    "userID": 50,
    "destinationID": 42,
    "travelers": 4,
    "date": "2021/01/09",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 44,
    "userID": 27,
    "destinationID": 43,
    "travelers": 3,
    "date": "2020/09/12",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 45,
    "userID": 45,
    "destinationID": 5,
    "travelers": 6,
    "date": "2020/09/06",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 46,
    "userID": 44,
    "destinationID": 33,
    "travelers": 2,
    "date": "2020/08/24",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 47,
    "userID": 28,
    "destinationID": 32,
    "travelers": 3,
    "date": "2019/12/10",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 48,
    "userID": 44,
    "destinationID": 14,
    "travelers": 6,
    "date": "2021/02/10",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 49,
    "userID": 45,
    "destinationID": 35,
    "travelers": 1,
    "date": "2020/05/14",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 50,
    "userID": 3,
    "destinationID": 16,
    "travelers": 5,
    "date": "2020/07/02",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 51,
    "userID": 16,
    "destinationID": 27,
    "travelers": 2,
    "date": "2020/01/16",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 52,
    "userID": 46,
    "destinationID": 14,
    "travelers": 2,
    "date": "2020/01/24",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 53,
    "userID": 27,
    "destinationID": 4,
    "travelers": 6,
    "date": "2020/01/03",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 54,
    "userID": 48,
    "destinationID": 21,
    "travelers": 2,
    "date": "2020/09/27",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 55,
    "userID": 39,
    "destinationID": 49,
    "travelers": 3,
    "date": "2020/03/08",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 56,
    "userID": 23,
    "destinationID": 21,
    "travelers": 3,
    "date": "2020/06/14",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 57,
    "userID": 33,
    "destinationID": 17,
    "travelers": 2,
    "date": "2019/07/04",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 58,
    "userID": 40,
    "destinationID": 36,
    "travelers": 4,
    "date": "2020/10/27",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 59,
    "userID": 21,
    "destinationID": 44,
    "travelers": 4,
    "date": "2020/01/27",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 60,
    "userID": 17,
    "destinationID": 45,
    "travelers": 2,
    "date": "2020/06/23",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 61,
    "userID": 26,
    "destinationID": 19,
    "travelers": 2,
    "date": "2020/07/25",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 62,
    "userID": 19,
    "destinationID": 37,
    "travelers": 4,
    "date": "2020/08/07",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 63,
    "userID": 26,
    "destinationID": 35,
    "travelers": 5,
    "date": "2020/11/03",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 64,
    "userID": 45,
    "destinationID": 25,
    "travelers": 3,
    "date": "2020/08/26",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 65,
    "userID": 3,
    "destinationID": 35,
    "travelers": 4,
    "date": "2020/03/21",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 66,
    "userID": 17,
    "destinationID": 31,
    "travelers": 6,
    "date": "2020/12/19",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 67,
    "userID": 36,
    "destinationID": 47,
    "travelers": 5,
    "date": "2020/04/25",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 68,
    "userID": 44,
    "destinationID": 41,
    "travelers": 6,
    "date": "2020/09/19",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 69,
    "userID": 40,
    "destinationID": 7,
    "travelers": 6,
    "date": "2019/11/16",
    "duration": 12,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 70,
    "userID": 21,
    "destinationID": 17,
    "travelers": 3,
    "date": "2019/10/01",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 71,
    "userID": 38,
    "destinationID": 28,
    "travelers": 1,
    "date": "2020/05/26",
    "duration": 11,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 72,
    "userID": 38,
    "destinationID": 25,
    "travelers": 2,
    "date": "2019/12/30",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 73,
    "userID": 17,
    "destinationID": 14,
    "travelers": 2,
    "date": "2020/04/26",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 74,
    "userID": 9,
    "destinationID": 31,
    "travelers": 5,
    "date": "2020/03/05",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 75,
    "userID": 34,
    "destinationID": 28,
    "travelers": 2,
    "date": "2020/12/30",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 76,
    "userID": 7,
    "destinationID": 17,
    "travelers": 5,
    "date": "2019/10/22",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 77,
    "userID": 7,
    "destinationID": 46,
    "travelers": 5,
    "date": "2020/05/28",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 78,
    "userID": 37,
    "destinationID": 17,
    "travelers": 3,
    "date": "2020/11/07",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 79,
    "userID": 39,
    "destinationID": 38,
    "travelers": 1,
    "date": "2020/11/01",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 80,
    "userID": 43,
    "destinationID": 21,
    "travelers": 1,
    "date": "2019/09/28",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 81,
    "userID": 10,
    "destinationID": 26,
    "travelers": 1,
    "date": "2020/08/31",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 82,
    "userID": 34,
    "destinationID": 15,
    "travelers": 1,
    "date": "2019/07/12",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 83,
    "userID": 47,
    "destinationID": 26,
    "travelers": 1,
    "date": "2020/05/06",
    "duration": 11,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 84,
    "userID": 7,
    "destinationID": 1,
    "travelers": 1,
    "date": "2020/11/23",
    "duration": 19,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 85,
    "userID": 14,
    "destinationID": 32,
    "travelers": 2,
    "date": "2020/02/21",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 86,
    "userID": 22,
    "destinationID": 46,
    "travelers": 4,
    "date": "2020/10/31",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 87,
    "userID": 42,
    "destinationID": 40,
    "travelers": 2,
    "date": "2020/03/17",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 88,
    "userID": 21,
    "destinationID": 21,
    "travelers": 6,
    "date": "2019/07/27",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 89,
    "userID": 2,
    "destinationID": 10,
    "travelers": 5,
    "date": "2019/09/27",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 90,
    "userID": 15,
    "destinationID": 38,
    "travelers": 5,
    "date": "2020/03/04",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 91,
    "userID": 5,
    "destinationID": 5,
    "travelers": 1,
    "date": "2020/04/29",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 92,
    "userID": 30,
    "destinationID": 4,
    "travelers": 2,
    "date": "2020/12/24",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 93,
    "userID": 40,
    "destinationID": 47,
    "travelers": 2,
    "date": "2019/12/08",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 94,
    "userID": 38,
    "destinationID": 12,
    "travelers": 3,
    "date": "2019/11/28",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 95,
    "userID": 9,
    "destinationID": 16,
    "travelers": 4,
    "date": "2020/05/29",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 96,
    "userID": 40,
    "destinationID": 31,
    "travelers": 3,
    "date": "2020/09/02",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 97,
    "userID": 7,
    "destinationID": 3,
    "travelers": 3,
    "date": "2020/08/20",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 98,
    "userID": 7,
    "destinationID": 12,
    "travelers": 6,
    "date": "2020/10/6",
    "duration": 16,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 99,
    "userID": 46,
    "destinationID": 27,
    "travelers": 1,
    "date": "2019/08/12",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 100,
    "userID": 2,
    "destinationID": 6,
    "travelers": 6,
    "date": "2020/3/28",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 101,
    "userID": 28,
    "destinationID": 9,
    "travelers": 1,
    "date": "2020/11/12",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  },
  {
    "id": 102,
    "userID": 3,
    "destinationID": 3,
    "travelers": 3,
    "date": "2020/09/26",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 103,
    "userID": 5,
    "destinationID": 35,
    "travelers": 2,
    "date": "2020/10/19",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 104,
    "userID": 26,
    "destinationID": 19,
    "travelers": 5,
    "date": "2020/03/04",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 105,
    "userID": 9,
    "destinationID": 14,
    "travelers": 2,
    "date": "2019/08/09",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 106,
    "userID": 9,
    "destinationID": 34,
    "travelers": 5,
    "date": "2020/06/08",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 107,
    "userID": 8,
    "destinationID": 19,
    "travelers": 3,
    "date": "2020/06/02",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 108,
    "userID": 49,
    "destinationID": 32,
    "travelers": 3,
    "date": "2019/08/28",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 109,
    "userID": 45,
    "destinationID": 12,
    "travelers": 1,
    "date": "2019/07/02",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 110,
    "userID": 39,
    "destinationID": 33,
    "travelers": 2,
    "date": "2020/04/15",
    "duration": 12,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 111,
    "userID": 40,
    "destinationID": 20,
    "travelers": 5,
    "date": "2020/07/28",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 112,
    "userID": 27,
    "destinationID": 32,
    "travelers": 2,
    "date": "2019/07/31",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 113,
    "userID": 22,
    "destinationID": 6,
    "travelers": 3,
    "date": "2019/08/14",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 114,
    "userID": 23,
    "destinationID": 9,
    "travelers": 1,
    "date": "2020/03/14",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 115,
    "userID": 36,
    "destinationID": 4,
    "travelers": 1,
    "date": "2019/12/03",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 116,
    "userID": 2,
    "destinationID": 7,
    "travelers": 3,
    "date": "2020/04/03",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 117,
    "userID": 1,
    "destinationID": 28,
    "travelers": 3,
    "date": "2021/01/09",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 118,
    "userID": 33,
    "destinationID": 19,
    "travelers": 5,
    "date": "2021/02/09",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 119,
    "userID": 10,
    "destinationID": 47,
    "travelers": 5,
    "date": "2020/05/28",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 120,
    "userID": 15,
    "destinationID": 33,
    "travelers": 1,
    "date": "2020/11/21",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 121,
    "userID": 3,
    "destinationID": 44,
    "travelers": 2,
    "date": "2020/03/11",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 122,
    "userID": 48,
    "destinationID": 17,
    "travelers": 2,
    "date": "2020/09/06",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 123,
    "userID": 7,
    "destinationID": 16,
    "travelers": 6,
    "date": "2020/05/03",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 124,
    "userID": 46,
    "destinationID": 3,
    "travelers": 6,
    "date": "2019/10/07",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 125,
    "userID": 19,
    "destinationID": 2,
    "travelers": 4,
    "date": "2019/12/22",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 126,
    "userID": 8,
    "destinationID": 26,
    "travelers": 5,
    "date": "2020/07/23",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 127,
    "userID": 24,
    "destinationID": 35,
    "travelers": 6,
    "date": "2019/11/13",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 128,
    "userID": 37,
    "destinationID": 13,
    "travelers": 1,
    "date": "2020/01/27",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 129,
    "userID": 36,
    "destinationID": 24,
    "travelers": 6,
    "date": "2019/08/23",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 130,
    "userID": 21,
    "destinationID": 49,
    "travelers": 6,
    "date": "2020/08/11",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 131,
    "userID": 46,
    "destinationID": 20,
    "travelers": 1,
    "date": "2020/09/23",
    "duration": 12,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 132,
    "userID": 42,
    "destinationID": 30,
    "travelers": 5,
    "date": "2020/09/07",
    "duration": 5,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 133,
    "userID": 48,
    "destinationID": 46,
    "travelers": 5,
    "date": "2019/09/15",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 134,
    "userID": 20,
    "destinationID": 50,
    "travelers": 6,
    "date": "2020/02/13",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 135,
    "userID": 38,
    "destinationID": 6,
    "travelers": 4,
    "date": "2020/04/02",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 136,
    "userID": 33,
    "destinationID": 24,
    "travelers": 5,
    "date": "2020/06/29",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 137,
    "userID": 23,
    "destinationID": 15,
    "travelers": 5,
    "date": "2019/09/26",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 138,
    "userID": 25,
    "destinationID": 22,
    "travelers": 3,
    "date": "2020/10/29",
    "duration": 18,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 139,
    "userID": 13,
    "destinationID": 7,
    "travelers": 5,
    "date": "2020/05/22",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 140,
    "userID": 46,
    "destinationID": 37,
    "travelers": 4,
    "date": "2021/01/18",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 141,
    "userID": 36,
    "destinationID": 19,
    "travelers": 5,
    "date": "2020/01/05",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 142,
    "userID": 42,
    "destinationID": 39,
    "travelers": 1,
    "date": "2019/12/14",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 143,
    "userID": 8,
    "destinationID": 7,
    "travelers": 3,
    "date": "2020/02/25",
    "duration": 12,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 144,
    "userID": 45,
    "destinationID": 13,
    "travelers": 2,
    "date": "2020/09/21",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 145,
    "userID": 7,
    "destinationID": 31,
    "travelers": 6,
    "date": "2020/04/01/",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 146,
    "userID": 44,
    "destinationID": 31,
    "travelers": 1,
    "date": "2020/02/05",
    "duration": 12,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 147,
    "userID": 8,
    "destinationID": 6,
    "travelers": 4,
    "date": "2019/09/18",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 148,
    "userID": 36,
    "destinationID": 30,
    "travelers": 1,
    "date": "2020/06/16",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 149,
    "userID": 18,
    "destinationID": 22,
    "travelers": 4,
    "date": "2019/10/01",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 150,
    "userID": 11,
    "destinationID": 20,
    "travelers": 5,
    "date": "2020/10/29",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 151,
    "userID": 46,
    "destinationID": 6,
    "travelers": 1,
    "date": "2020/02/11",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 152,
    "userID": 30,
    "destinationID": 40,
    "travelers": 1,
    "date": "2020/03/26",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 153,
    "userID": 39,
    "destinationID": 31,
    "travelers": 2,
    "date": "2021/02/27",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 154,
    "userID": 46,
    "destinationID": 3,
    "travelers": 4,
    "date": "2020/12/11",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 155,
    "userID": 43,
    "destinationID": 49,
    "travelers": 4,
    "date": "2020/05/16",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 156,
    "userID": 48,
    "destinationID": 40,
    "travelers": 1,
    "date": "2019/08/02",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 157,
    "userID": 33,
    "destinationID": 41,
    "travelers": 1,
    "date": "2020/01/12",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 158,
    "userID": 31,
    "destinationID": 32,
    "travelers": 6,
    "date": "2020/09/03",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 159,
    "userID": 25,
    "destinationID": 42,
    "travelers": 6,
    "date": "2020/07/24",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 160,
    "userID": 41,
    "destinationID": 28,
    "travelers": 6,
    "date": "2019/10/12",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 161,
    "userID": 44,
    "destinationID": 48,
    "travelers": 6,
    "date": "2020/08/13",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 162,
    "userID": 48,
    "destinationID": 25,
    "travelers": 2,
    "date": "2020/06/22",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 163,
    "userID": 5,
    "destinationID": 48,
    "travelers": 1,
    "date": "2020/04/28",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 164,
    "userID": 33,
    "destinationID": 25,
    "travelers": 4,
    "date": "2019/11/30",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 165,
    "userID": 40,
    "destinationID": 15,
    "travelers": 6,
    "date": "2019/10/19",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 166,
    "userID": 2,
    "destinationID": 7,
    "travelers": 2,
    "date": "2020/03/05",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 167,
    "userID": 15,
    "destinationID": 42,
    "travelers": 3,
    "date": "2019/08/10",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 168,
    "userID": 15,
    "destinationID": 30,
    "travelers": 3,
    "date": "2020/04/15",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 169,
    "userID": 23,
    "destinationID": 15,
    "travelers": 1,
    "date": "2020/01/12",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 170,
    "userID": 15,
    "destinationID": 1,
    "travelers": 2,
    "date": "2019/10/30",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 171,
    "userID": 2,
    "destinationID": 43,
    "travelers": 1,
    "date": "2020/12/27",
    "duration": 18,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 172,
    "userID": 17,
    "destinationID": 38,
    "travelers": 5,
    "date": "2020/06/17",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 173,
    "userID": 3,
    "destinationID": 9,
    "travelers": 6,
    "date": "2020/04/21",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 174,
    "userID": 13,
    "destinationID": 47,
    "travelers": 5,
    "date": "2020/5/15",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 175,
    "userID": 45,
    "destinationID": 40,
    "travelers": 5,
    "date": "2019/09/05",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 176,
    "userID": 37,
    "destinationID": 4,
    "travelers": 1,
    "date": "2020/08/13",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 177,
    "userID": 2,
    "destinationID": 20,
    "travelers": 6,
    "date": "2020/01/29",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 178,
    "userID": 33,
    "destinationID": 40,
    "travelers": 2,
    "date": "2019/12/25",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 179,
    "userID": 18,
    "destinationID": 21,
    "travelers": 1,
    "date": "2020/10/30",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 180,
    "userID": 48,
    "destinationID": 14,
    "travelers": 1,
    "date": "2020/09/06",
    "duration": 12,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 181,
    "userID": 41,
    "destinationID": 23,
    "travelers": 4,
    "date": "2019/11/29",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 182,
    "userID": 9,
    "destinationID": 45,
    "travelers": 6,
    "date": "2021/01/15",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 183,
    "userID": 44,
    "destinationID": 10,
    "travelers": 4,
    "date": "2020/07/22",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 184,
    "userID": 17,
    "destinationID": 11,
    "travelers": 1,
    "date": "2019/12/27",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 185,
    "userID": 10,
    "destinationID": 35,
    "travelers": 4,
    "date": "2019/09/02",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 186,
    "userID": 4,
    "destinationID": 44,
    "travelers": 6,
    "date": "2020/02/08",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 187,
    "userID": 43,
    "destinationID": 14,
    "travelers": 3,
    "date": "2020/11/12",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 188,
    "userID": 26,
    "destinationID": 33,
    "travelers": 6,
    "date": "2020/11/28",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 189,
    "userID": 25,
    "destinationID": 15,
    "travelers": 4,
    "date": "2019/12/01",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 190,
    "userID": 8,
    "destinationID": 9,
    "travelers": 5,
    "date": "2019/09/13",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 191,
    "userID": 6,
    "destinationID": 47,
    "travelers": 5,
    "date": "2019/08/17",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 192,
    "userID": 29,
    "destinationID": 48,
    "travelers": 5,
    "date": "2019/09/24",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 193,
    "userID": 12,
    "destinationID": 35,
    "travelers": 1,
    "date": "2020/11/09",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 194,
    "userID": 34,
    "destinationID": 14,
    "travelers": 1,
    "date": "2020/07/10",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 195,
    "userID": 22,
    "destinationID": 17,
    "travelers": 3,
    "date": "2019/09/12",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 196,
    "userID": 5,
    "destinationID": 16,
    "travelers": 1,
    "date": "2020/09/25",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 197,
    "userID": 49,
    "destinationID": 5,
    "travelers": 6,
    "date": "2020/07/27",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 198,
    "userID": 45,
    "destinationID": 46,
    "travelers": 1,
    "date": "2019/11/04",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 199,
    "userID": 45,
    "destinationID": 39,
    "travelers": 6,
    "date": "2020/05/17",
    "duration": 6,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 200,
    "userID": 29,
    "destinationID": 23,
    "travelers": 6,
    "date": "2020/06/29",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }
];

module.exports = { trips };
