const musicVenues = [
  { "name": "Bluebird Theater", "address": "3317 E Colfax Ave, Denver, CO 80206", "capacity": 550, "phone": "(303)377-1666"},
  { "name": "Ogden Theater", "address": "935 E Colfax Ave, Denver, CO 80218", "capacity": 1600, "phone": "(303)832-1874"},
  { "name": "Filmore Auditorium", "address": "1510 N Clarkson St, Denver, CO 80218", "capacity": 3900, "phone": "(303)837-0360"},
  { "name": "Herman's Hideway", "address": "1578 S Broadway, Denver, CO 80210", "phone": "(303)777-5840"},
  { "name": "Cervantes", "address": "2637 Welton St, Denver, CO 80205", "phone": "(303)297-1772"},
  { "name": "Marquis Theater", "address": "2009 Larimer St, Denver, CO 80205", "genres": ["indie"], "phone": "(303)487-0111"},
  { "name": "Summit", "address": "1902 Blake St, Denver, CO 80202", "genres": ["metal", "punk"], "phone": "(303)487-0111"},
  { "name": "Seventh Circle Music Collective", "address": "2935 W 7th Ave, Denver, CO 80204", "genres": ["indie", "local"]},
  { "name": "Red Rocks Amphitheatre", "address": "18300 W Alameda Pkwy, Morrison, CO 80465", "capacity": 9525, "phone": "(720)865-2494"},
  { "name": "Levitt Pavilion Denver", "address": "1380 W Florida Ave, Denver, CO 80223", "phone": "(303)578-0488"},
  { "name": "El Chapultepec", "address": "1962 Market St, Denver, CO 80202", "genres": ["Jazz"], "phone": "(303)295-9126"},
  { "name": "Globe Hall", "address": "4483 Logan St, Denver, CO 80216", "phone": "(303)296-1003"},
  { "name": "The Grizzly Rose", "address": "5450 N Valley Hwy, Denver, CO 80216", "genres": ["country"], "phone": "(303) 295-2353"},
  { "name": "Oriental Theater", "address": "4335 W 44th Ave, Denver, CO 80212", "phone": "(720)420-0030"},
  { "name": "Larimer Lounge", "address": "2721 Larimer St, Denver, CO 80205", "genres": ["punk", "alternative"], "phone": "(303)291-1007"},
  { "name": "Buffalo Rose Saloon", "address": "1119 Washington Ave, Golden, CO 80401", "phone": "(720)638-5597"},
  { "name": "The Venue", "address": "1451 Cortez St, Denver, CO 80221", "phone": "(303)428-3339"},
  { "name": "Dazzle", "address": "1512 Curtis Street, Denver, CO 80202", "genres": ["Jazz"], "phone": "(303)839-5100"},
  { "name": "Gothic Theatre", "address": "3263 S Broadway, Englewood, CO 80113", "capacity": 1100, "phone": "(303)789-9206"},
  { "name": "Fiddler's Green Amphitheatre", "address": "6350 Greenwood Plaza Blvd, Greenwood Village, CO 80111", "capacity": 18000, "phone": "(303)220-7000"},
  { "name": "1STBANK Center", "address": "11450 Broomfield Ln, Broomfield, CO 80021", "capacity": 6500, "phone": "(303)410-0700"},
  { "name": "Macky Auditorium Concert Hall", "address": "1595 Pleasant St, Boulder, CO 80309", "phone": "(303)492-8423"},
  { "name": "The Fox Theatre", "address": "1135 13th St, Boulder, CO 80302", "capacity": 500, "phone": "(303)447-0095"},
  { "name": "Boulder Theater", "address": "2032 14th St, Boulder, CO 80302", "capacity": 850, "phone": "(303)786-7030"},
  { "name": "Aggie Theatre", "address": "204 S College Ave, Fort Collins, CO 80524", "phone": "(833)244-4348"},
  { "name": "The Black Box", "address": "314 E 13th Ave, Denver, CO 80203", "genres": ["dance", "DJ", "electronic"]},
  { "name": "The Church Nightclub", "address": "1160 Lincoln St, Denver, CO 80203", "genres": ["dance", "DJ", "electronic"], "phone": "(303)832-2383"},
  { "name": "Club Vinyl", "address": "1082 Broadway, Denver, CO 80203", "genres": ["dance", "DJ", "electronic"], "phone": "(303)860-8469"},
  { "name": "Hi-Dive", "address": "7 S Broadway, Denver, CO 80223", "phone": "(303)733-0230"},
  { "name": "PEPSI Center", "address": "1000 Chopper Cir, Denver, CO 80204", "capacity": 18007, "phone": "(303)405-1100"},
  { "name": "Swallow Hill Music", "address": "71 E Yale Ave, Denver, CO 80210", "genres": ["indie", "folk", "acoustic"], "phone": "(303)777-1003"}
];

const bands = [
  { "bandName": "Ganja White Knight", "upcomingVenues": ["Bluebird Theater", "The Fox Theatre", "The Church Nightclub"] },
  { "bandName": "Jeremy Zucker", "upcomingVenues": ["Larimer Lounge", "The Venue"] },
  { "bandName": "Miles Davis", "upcomingVenues": ["Dazzle", "El Chapultepec"] },
  { "bandName": "Redman", "upcomingVenues": ["PEPSI Center", "The Black Box"] },
  { "bandName": "Oh Wonder", "upcomingVenues": ["Gothic Theatre", "Boulder Theater"] },
  { "bandName": "Caamp", "upcomingVenues": ["Red Rocks Amphitheatre", "Filmore Auditorium"] },
  { "bandName": "Rainbow Kitten Surprise", "upcomingVenues": ["Red Rocks Amphitheatre", "Ogden Theater"] },
  { "bandName": "Riz La Vie", "upcomingVenues": ["Summit", "Cervantes", "1STBANK Center"] },
  { "bandName": "Rufus Du Sol", "upcomingVenues": ["Boulder Theater", "Hi-Dive"] },
  { "bandName": "Mt. Joy", "upcomingVenues": ["The Fox Theatre", "Oriental Theater"] },
  { "bandName": "Still Woozy", "upcomingVenues": ["Marquis Theater", "Club Vinyl"] },
  { "bandName": "Sungha Jung", "upcomingVenues": ["Herman's Hideway", "Macky Auditorium Concert Hall", "Swallow Hill Music"] },
  { "bandName": "Two Feet", "upcomingVenues": ["Aggie Theatre", "1STBANK Center"] },
  { "bandName": "Weezer", "upcomingVenues": ["1STBANK Center", "PEPSI Center"] },
  { "bandName": "50 Cent", "upcomingVenues": ["PEPSI Center", "Fiddler's Green Amphitheatre"] },
  { "bandName": "Alison Wonderland", "upcomingVenues": ["Aggie Theatre", "The Black Box"] },
  { "bandName": "Amine", "upcomingVenues": ["Globe Hall", "Marquis Theater"] },
  { "bandName": "Arctic Monkeys", "upcomingVenues": ["Marquis Theater", "Red Rocks Amphitheatre"] },
  { "bandName": "Avenged Seven Fold", "upcomingVenues": ["1STBANK Center", "Levitt Pavilion Denver", "Boulder Theater"] },
  { "bandName": "Cage The Elephant", "upcomingVenues": ["Boulder Theater", "Fiddler's Green Amphitheatre"] },
  { "bandName": "Charles Bradley", "upcomingVenues": ["Buffalo Rose Saloon", "Seventh Circle Music Collective", "Summit", "Dazzle"] },
  { "bandName": "Chelsea Cutler", "upcomingVenues": ["Larimer Lounge", "Seventh Circle Music Collective", "Bluebird Theater"] },
  { "bandName": "Childish Gambino", "upcomingVenues": ["PEPSI Center", "Filmore Auditorium"] },
  { "bandName": "Cruel Youth", "upcomingVenues": ["Gothic Theatre", "Marquis Theater"] },
  { "bandName": "Daughter", "upcomingVenues": ["Oriental Theater", "Levitt Pavilion Denver"] },
  { "bandName": "Eddie Vedder", "upcomingVenues": ["The Grizzly Rose", "Hi-Dive"] },
  { "bandName": "Elohim", "upcomingVenues": ["Club Vinyl", "The Church Nightclub", "Filmore Auditorium"] },
  { "bandName": "Jonny Cash", "upcomingVenues": ["The Grizzly Rose", "Buffalo Rose Saloon", "Macky Auditorium Concert Hall"] },
  { "bandName": "Gabriel Black", "upcomingVenues": ["Bluebird Theater", "Gothic Theatre", "The Venue"] },
  { "bandName": "John Craige", "upcomingVenues": ["Buffalo Rose Saloon", "Globe Hall", "El Chapultepec"] },
  { "bandName": "Parliament", "upcomingVenues": ["Cervantes", "Oriental Theater", "Summit"] },
  { "bandName": "Willie Nelson", "upcomingVenues": ["The Grizzly Rose", "Filmore Auditorium", "Swallow Hill Music"] }
];