const data = {
  films: [
    {Title: 'Black Panther', Rating: 97, numReviews: 460, director: 'Ryan Coogler'},
    {Title: 'Lady Bird', Rating: 99, numReviews: 359, director: 'Greta Gerwig'},
    {Title: 'The Wizard of Oz', Rating: 98, numReviews: 111, director: 'Victor Fleming'},
    {Title: 'Citizen Kane', Rating: 100, numReviews: 80, director: 'Orson Wells'},
    {Title: 'BlackKKlansman', Rating: 96, numReviews: 390, director: 'Spike Lee'},
    {Title: 'Get Out', Rating: 98, numReviews: 347, director: 'Jordan Peele'},
    {Title: 'The Third Man', Rating: 99, numReviews: 78, director: 'Carol Reed'},
    {Title: 'Mad Max: Fury Road', Rating: 97, numReviews: 399, director: 'George Miller'},
    {Title: 'Moonlight', Rating: 98, numReviews: 353, director: 'Berry Jenkins'},
    {Title: 'inside Out', Rating: 98, numReviews: 350, director: 'Pete Docter'},
    {Title: 'Wonder Woman', Rating: 93, numReviews: 422, director: 'Patty Jenkins'},
    {Title: 'The Cabinet of Dr. Caligari', Rating: 100, numReviews: 50, director: 'Robert Wiene'},
    {Title: 'All About Eve', Rating: 100, numReviews: 66, director: 'Joseph Mankiewicz'},
    {Title: 'Metropolis', Rating: 99, numReviews: 121, director: 'Fritz Lang'},
    {Title: 'E.T. The Extra-Terrestrial', Rating: 98, numReviews: 125, director: 'Steven Spielberge'},
    {Title: 'CoCo', Rating: 97, numReviews: 317, director: 'Joseph Mankiewicz'},
    {Title: 'It Happened One Night', Rating: 98, numReviews: 56, director: 'Frank Capra'},
    {Title: 'A Quiet Place', Rating: 95, numReviews: 343, director: 'John Krasinski'},
    {Title: 'Dunkirk', Rating: 92, numReviews: 424, director: 'Christopher Nolan'},
    {Title: 'Spotlight', Rating: 97, numReviews: 349, director: 'Tom McCarthy'},
    {Title: 'Eight Grade', Rating: 99, numReviews: 252, director: 'Bo Burnham'},
    {Title: 'Selma', Rating: 99, numReviews: 294, director: 'Ava DuVernay'},
    {Title: 'Casablanca', Rating: 97, numReviews: 79, director: 'Michael Curtiz'},
    {Title: 'Modern Times', Rating: 100, numReviews: 54, director: 'Charles Chaplin'},
    {Title: 'Paddington 2', Rating: 100, numReviews: 226, director: 'Paul King VII'},
    {Title: 'The Big Sick', Rating: 98, numReviews: 280, director: 'Michael Showalter'},
    {Title: 'Star Wars: The Last Jedi', Rating: 98, numReviews: 430, director: 'Rian Johnson'},
    {Title: 'The Godfather', Rating: 98, numReviews: 89, director: 'Francis Ford Coppola'},
    {Title: 'Arrival', Rating: 94, numReviews: 395, director: 'Denis Villeneuve'},
    {Title: 'La Grande Illusion', Rating: 97, numReviews: 66, director: 'Jean Renoir'},
  ]
  Ratings: [
    {ratingPercentage: 100, numMovies: 5},
    {ratingPercentage: 99, numMovies: 5},
    {ratingPercentage: 98, numMovies: 9},
    {ratingPercentage: 97, numMovies: 6},
    {ratingPercentage: 96, numMovies: 1},
    {ratingPercentage: 95, numMovies: 1},
    {ratingPercentage: 94, numMovies: 1},
    {ratingPercentage: 93, numMovies: 1},
    {ratingPercentage: 92, numMovies: 1},
  ]
}