const climbingPlaces = [
	{ "place": "Golden Cliffs",
	  "closestTown": "Golden, Colorado",
	  "climbingId": 1 },
	{ "place": "Clear Creek Canyon",
		"closestTown": "Golden, Colorado",
		"climbingId": 2 },
	{ "place": "Boulder Canyon",
		"closestTown": "Boulder, Colorado",
		"climbingId": 3 },
	{ "place": "Garden of The Gods",
		"closestTown": "Colorado Springs, Colorado"
		"climbingId": 4 },
	{ "place": "The Flat Irons",
		"closestTown": "Boulder, Colorado" 
		"climbingId": 5 },
	{ "place": "Castlewood Canyon State Park",
		"closestTown": "Castle Rock, Colorado"
		"climbingId": 6 },
	{ "place": "Eldorado Canyon State Park",
		"closestTown": "Boulder, Colorado", 
		"climbingId": 7 },
	{	"place": "Greyrock",
		"closetTown": "Fort Collins, Colorado",
		"climbingId": 8 },
	{	"place": "South Platte Domes",
		"closetTown": "Sedalia, Colorado",
		"climbingId": 9 },
	{	"place": "Rampart Range",
		"closetTown": "Sedalia, Colorado",
		"climbingId": 10 }
	];

	const routes = [
		{ "climbingPlaceId": 1,
			"area": "Brown Cloud Crags",
			"routeName": "Louise",
			"difficultyLevel": "5.8",
			"type": ["sport"] },
		{ "climbingPlaceId": 1,
			"area": "Brown Cloud Crags",
			"routeName": "Thelma",
			"difficultyLevel": "5.7",
			"type": ["sport"] },
		{ "climbingPlaceId": 1,
			"area": "Brown Cloud Crags",
			"routeName": "Pee on D",
			"difficultyLevel": "5.8",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 1,
			"area": "Brown Cloud Crags",
			"routeName": "Killian's Dead",
			"difficultyLevel": "5.6",
			"type": ["trad"] },
		{ "climbingPlaceId": 1,
			"area": "Brown Cloud Crags",
			"routeName": "Lemons, Limes, and Tangerines",
			"difficultyLevel": "5.8",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 1,
			"area": "Overhang Area",
			"routeName": "Mister Squirrel Places a Nut",
			"difficultyLevel": "5.11c",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 1,
			"area": "Overhang Area",
			"routeName": "Offline",
			"difficultyLevel": "5.8",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 1,
			"area": "Overhang Area",
			"routeName": "Corniche",
			"difficultyLevel": "5.8",
			"type": ["trad"] },
		{ "climbingPlaceId": 1,
			"area": "Overhang Area",
			"routeName": "In Between the Lines",
			"difficultyLevel": "5.9",
			"type": ["sport", "top-rope"] },
	 { "climbingPlaceId": 1,
			"area": "Overhang Area",
			"routeName": "Sidelines",
			"difficultyLevel": "5.10a",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 2,
			"area": "Sports Wall",
			"routeName": "Rufus Roof",
			"difficultyLevel": "5.12b",
			"type": ["top-rope"] },
		{ "climbingPlaceId": 2,
			"area": "Sports Wall",
			"routeName": "Olaf's Roof",
			"difficultyLevel": "5.11b",
			"type": ["top-rope", "trad"] },
		{ "climbingPlaceId": 2,
			"area": "Sports Wall",
			"routeName": "Coffin Crack",
			"difficultyLevel": "5.9",
			"type": ["trad"] },
		{ "climbingPlaceId": 2,
			"area": "Anarchy Wall",
			"routeName": "Question Authority",
			"difficultyLevel": "5.12a",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 2,
			"area": "Anarchy Wall",
			"routeName": "Chaos",
			"difficultyLevel": "5.13a",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 2,
			"area": "Anarchy Wall",
			"routeName": "Halloween",
			"difficultyLevel": "5.7",
			"type": ["sport"] },
		{ "climbingPlaceId": 2,
			"area": "Monkey Wrench",
			"routeName": "Question Authority",
			"difficultyLevel": "5.11c",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 3,
			"area": "The Dome",
			"routeName": "East Slab",
			"difficultyLevel": "5.5",
			"type": ["trad"] },
		{ "climbingPlaceId": 3,
			"area": "The Dome",
			"routeName": "Cozyhang",
			"difficultyLevel": "5.7",
			"type": ["trad"] },
		{ "climbingPlaceId": 3,
			"area": "The Dome",
			"routeName": "The Owl",
			"difficultyLevel": "5.7",
			"type": ["trad"] },
		{ "climbingPlaceId": 3,
			"area": "The Dome",
			"routeName": "Super Squeeze",
			"difficultyLevel": "5.10d",
			"type": ["trad"] },
		{ "climbingPlaceId": 4,
			"area": "North Gateway Rock",
			"routeName": "Anaconda",
			"difficultyLevel": "5.11c",
			"type": ["trad"] },
		{ "climbingPlaceId": 4,
			"area": "North Gateway Rock",
			"routeName": "Grapefruit Dance",
			"difficultyLevel": "5.12a",
			"type": ["sport"] },
		{ "climbingPlaceId": 4,
			"area": "North Gateway Rock",
			"routeName": "Rainbow Bridge",
			"difficultyLevel": "5.11a",
			"type": ["sport"] },
		{ "climbingPlaceId": 4,
			"area": "North Gateway Rock",
			"routeName": "Over the Rainbow",
			"difficultyLevel": "5.11a",
			"type": ["sport"] },
		{ "climbingPlaceId": 4,
			"area": "South Gateway Rock",
			"routeName": "Candyman",
			"difficultyLevel": "5.10c",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 4,
			"area": "South Gateway Rock",
			"routeName": "Cocaine",
			"difficultyLevel": "5.10b",
			"type": ["sport"] },
		{ "climbingPlaceId": 4,
			"area": "South Gateway Rock",
			"routeName": "Cold Turkey",
			"difficultyLevel": "5.11b",
			"type": ["sport"] },
		{ "climbingPlaceId": 4,
			"area": "South Gateway Rock",
			"routeName": "East Slab",
			"difficultyLevel": "5.5",
			"type": ["trad"] },
		{ "climbingPlaceId": 4,
			"area": "Red Twin Spires",
			"routeName": "Potholes",
			"difficultyLevel": "5.7",
			"type": ["sport"] },
		{ "climbingPlaceId": 4,
			"area": "Whitetwin Spire",
			"routeName": "South Ridge",
			"difficultyLevel": "5.6",
			"type": ["top-rope", "trad"] },
		{ "climbingPlaceId": 5,
			"area": "First Flatiron",
			"routeName": "Direct East Face",
			"difficultyLevel": "5.6",
			"type": ["trad"] },
		{ "climbingPlaceId": 5,
			"area": "First Flatiron",
			"routeName": "Fandango",
			"difficultyLevel": "5.6",
			"type": ["trad"] },
		{ "climbingPlaceId": 5,
			"area": "Third Flatiron",
			"routeName": "College Dropout",
			"difficultyLevel": "5.7",
			"type": ["trad"] },
		{ "climbingPlaceId": 5,
			"area": "First Flatiron",
			"routeName": "Extra Point",
			"difficultyLevel": "5.7",
			"type": ["trad"] },
		{ "climbingPlaceId": 6,
			"area": "Falls Wall",
			"routeName": "Swinging Sirloin",
			"difficultyLevel": "5.11c",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 6,
			"area": "Falls Wall",
			"routeName": "Out of Arms Reach",
			"difficultyLevel": "5.10b",
			"type": ["sport"] },
		{ "climbingPlaceId": 6,
			"area": "Falls Wall",
			"routeName": "Arborist Arms",
			"difficultyLevel": "5.11a",
			"type": ["sport"] },
		{ "climbingPlaceId": 6,
			"area": "Falls Wall",
			"routeName": "Invaders From the North",
			"difficultyLevel": "5.11b",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 6,
			"area": "Falls Wall",
			"routeName": "Bones",
			"difficultyLevel": "5.13c",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 6,
			"area": "Falls Wall",
			"routeName": "It's Flakey",
			"difficultyLevel": "5.7",
			"type": ["trad"] },
		{ "climbingPlaceId": 6,
			"area": "Project X Wall",
			"routeName": "Skunk Buddress",
			"difficultyLevel": "5.10",
			"type": ["sport"] },
		{ "climbingPlaceId": 6,
			"area": "Project X Wall",
			"routeName": "Rest in Pieces",
			"difficultyLevel": "5.9",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 6,
			"area": "Project X Wall",
			"routeName": "Project X",
			"difficultyLevel": "5.12a",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 7,
			"area": "Redgarden Wall",
			"routeName": "C'est La Vie",
			"difficultyLevel": "5.11a",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 7,
			"area": "Redgarden Wall",
			"routeName": "Desdichado",
			"difficultyLevel": "5.13b",
			"type": ["sport"] },
		{ "climbingPlaceId": 7,
			"area": "Redgarden Wall",
			"routeName": "Genesis",
			"difficultyLevel": "5.12d",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 7,
			"area": "Whale's Tail",
			"routeName": "The Monument",
			"difficultyLevel": "5.12c",
			"type": ["sport"] },
		{ "climbingPlaceId": 7,
			"area": "Whale's Tail",
			"routeName": "West Crack",
			"difficultyLevel": "5.2",
			"type": ["trad"] },
		{ "climbingPlaceId": 7,
			"area": "Whale's Tail",
			"routeName": "West Dihedral",
			"difficultyLevel": "5.4",
			"type": ["trad"] },
		{ "climbingPlaceId": 7,
			"area": "Whale's Tail",
			"routeName": "Clementine",
			"difficultyLevel": "5.5",
			"type": ["trad"] },
		{ "climbingPlaceId": 8,
			"area": "South Slabs",
			"routeName": "Fun Flake",
			"difficultyLevel": "5.6",
			"type": ["trad"] },
		{ "climbingPlaceId": 8,
			"area": "South Slabs",
			"routeName": "Minds Meat",
			"difficultyLevel": "5.7",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 8,
			"area": "South Slabs",
			"routeName": "Bad Boys Bolt",
			"difficultyLevel": "5.11b",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 8,
			"area": "South Slabs",
			"routeName": "Black Market",
			"difficultyLevel": "5.11b",
			"type": ["sport"] },
		{ "climbingPlaceId": 9,
			"area": "Bucksnort Slab",
			"routeName": "Overlooked",
			"difficultyLevel": "5.9",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 9,
			"area": "Bucksnort Slab",
			"routeName": "Leftout",
			"difficultyLevel": "5.10a",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 9,
			"area": "Bucksnort Slab",
			"routeName": "Buck Fever",
			"difficultyLevel": "5.9",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 9,
			"area": "Bucksnort Slab",
			"routeName": "Shake 'n' Bake",
			"difficultyLevel": "5.10d",
			"type": ["sport", "top-rope", "trad"] },
		{ "climbingPlaceId": 9,
			"area": "The Dome",
			"routeName": "A Day At The Beach",
			"difficultyLevel": "5.9",
			"type": ["trad"] },
		{ "climbingPlaceId": 9,
			"area": "The Dome",
			"routeName": "Stars of Mars",
			"difficultyLevel": "5.10a",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 9,
			"area": "The Dome",
			"routeName": "Dos Equis",
			"difficultyLevel": "5.10c",
			"type": ["trad"] },
		{ "climbingPlaceId": 9,
			"area": "The Dome",
			"routeName": "Sea of Holes",
			"difficultyLevel": "5.11a",
			"type": ["sport"] },
		{ "climbingPlaceId": 10,
			"area": "Approach Boulder",
			"routeName": "Old Yeller",
			"difficultyLevel": "5.10c",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 10,
			"area": "Approach Boulder",
			"routeName": "Walking the Dog",
			"difficultyLevel": "5.8",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 10,
			"area": "Approach Boulder",
			"routeName": "Doggin the Walk",
			"difficultyLevel": "5.8",
			"type": ["sport", "top-rope"] },
		{ "climbingPlaceId": 10,
			"area": "Approach Boulder",
			"routeName": "GreyHound",
			"difficultyLevel": "5.11c",
			"type": ["top-rope"] },
		{ "climbingPlaceId": 10,
			"area": "Dog Slab",
			"routeName": "Atta Boy",
			"difficultyLevel": "5.8",
			"type": ["trad"] },
		{ "climbingPlaceId": 10,
			"area": "Dog Slab",
			"routeName": "The Mut",
			"difficultyLevel": "5.8",
			"type": ["trad"] },
		{ "climbingPlaceId": 10,
			"area": "Dog Slab",
			"routeName": "Hot Poop",
			"difficultyLevel": "5.8",
			"type": ["sport", "top-rope"] },
	];

	module.exports = {
		climbingPlaces,
		routes
	}
