const restaurants = [
   { 
   "name" : "Denver Biscuit Co.",
   "tags" : "Sandwiches, Breakfast",
   "cost" : "$$",
   "stars" : "4.72",
   "rank" : "1",
   "address" : "3237 E Colfax Ave, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/NiiTDBCR0Fgw0yD6wC66WQ/ls.jpg"
   },
   {
   "name" : "Snooze, An A.M. Eatery",
   "tags" : "Breakfast, Sandwiches, Coffee & Tea",
   "cost" : "$$",
   "stars" : "4.48",
   "rank" : "2",
   "address" : "2262 Larimer St, Denver, COc",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/QdozUJPNZ2rfQMJcZvMfgw/ls.jpg"
   },
   {
   "name" : "Root Down",
   "tags" : "American Food, Vegan, Vegetarian Restaurants",
   "cost" : "$$",
   "stars" : "4.46",
   "rank" : "3",
   "address" : "1600 W 33rd Ave, Denver, CO",
   "img" : "https://s3-media2.fl.yelpcdn.com/bphoto/21eJsFMltbsHGicq5__7LQ/ls.jpg"
   },
   {
   "name" : "Rioja",
   "tags" : "American Food, Spanish, Bars",
   "cost" : "$$$",
   "stars" : "4.43",
   "rank" : "4",
   "address" : "1431 Larimer St, Denver, CO",
   "img" : "https://s3-media2.fl.yelpcdn.com/bphoto/10nJgzsK4Fb_EeoiCGV7nQ/ls.jpg"
   },
   {
   "name" : "Linger",
   "tags" : "Asian Fusion, Breakfast, Bars",
   "cost" : "",
   "stars" : "",
   "rank" : "4.24",
   "address" : "2030 W 30th Ave, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/_5mQyB29yVKHu-uNp8P2Qw/ls.jpg"
   },
   {
   "name" : "Euclid Hall Bar & Kitchen",
   "tags" : "American Food, Bars",
   "cost" : "$$",
   "stars" : "4.12",
   "rank" : "6",
   "address" : "1317 14th St, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/BIYnxEFUVhMZ-83SsvVBIA/ls.jpg"
   },
   {
   "name" : "Work & Class",
   "tags" : "American Food, Latin Restaurants, Cocktail Bars",
   "cost" : "$$",
   "stars" : "4.43",
   "rank" : "7",
   "address" : "2500 Larimer St, Ste 101, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/wknJ1nD0jTQssiXfW-tjFQ/ls.jpg"
   },
   {
   "name" : "Steuben's Uptown",
   "tags" : "Diners, Breakfast, Cocktail Bars",
   "cost" : "$$",
   "stars" : "4.1",
   "rank" : "8",
   "address" : "523 E 17th Ave, Denver CO",
   "img" : "https://s3-media3.fl.yelpcdn.com/bphoto/iPEj2KIB41JR844HgsWXyQ/ls.jpg"
   },
   {
   "name" : "Chop Shop Casual Urban Eatery Colfax",
   "tags" : "American Food, Burgers, Salads",
   "cost" : "$$",
   "stars" : "4.53",
   "rank" : "9",
   "address" : "4990 Colfax Ave, Denver CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/-zhsCPiPRGBmeu1JkiRvNA/ls.jpg"
   },
   {
   "name" : "Sushi Den",
   "tags" : "Japanese Food, Sushi, Bars",
   "cost" : "$$$",
   "stars" : "4.45",
   "rank" : "10",
   "address" : "1487 S Pearl St, Denver, CO",
   "img" : "https://s3-media2.fl.yelpcdn.com/bphoto/5eiwXYSiTKsOwoHP0G84GQ/ls.jpg"
   },
   {
   "name" : "Biker Jim's Gourmet Dogs",
   "tags" : "Hot Dogs",
   "cost" : "$",
   "stars" : "4.63",
   "rank" : "11",
   "address" : "2148 Larimer St, Denver, CO",
   "img" : "https://s3-media2.fl.yelpcdn.com/bphoto/6KeKKAwblPG4OimhiBh7Gw/ls.jpg"
   },
   {
   "name" : "Osteria Marco",
   "tags" : "Italian, Pizza, Bars",
   "cost" : "1453 Larimer St, Denver, CO",
   "stars" : "3.93",
   "rank" : "12",
   "address" : "1453 Larimer St, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/P1xn_YGc0dx0Kg5TGrbPJw/ls.jpg"
   },
   {
   "name" : "Cherry Cricket",
   "tags" : "Burgers, Sports Bars",
   "cost" : "$$",
   "stars" : "4.12",
   "rank" : "13",
   "address" : "2641 E 2nd Ave, Denver, CO",
   "img" : "https://s3-media3.fl.yelpcdn.com/bphoto/Exy1ooWg6fK49nLeRlJimw/ls.jpg"
   },
   {
   "name" : "Guard and Grace",
   "tags" : "Steak, Wine Bars, Seafood",
   "cost" : "$$$",
   "stars" : "3.98",
   "rank" : "14",
   "address" : "1801 California St, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/C_La-hFnzYUy0dRXDphApA/ls.jpg"
   },  
   {
   "name" : "Angelo's Taverna",
   "tags" : "Italian, Seafood, Bars",
   "cost" : "$$",
   "stars" : "4.42",
   "rank" : "15",
   "address" : "620 E 6th Ave, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/P9V_zE_HGOuBSEyF4xkukA/ls.jpg"
   },
   {
   "name" : "WaterCourse Foods",
   "tags" : "Vegetarian Restaurants, Vegan, Comfort Food",
   "cost" : "$$",
   "stars" : "3.87",
   "rank" : "16",
   "address" : "837 E 17th Ave, Denver, CO",
   "img" : "https://s3-media3.fl.yelpcdn.com/bphoto/q1j8SnBXPWkauMzPu9b-Rg/ls.jpg"
   },
   {
   "name" : "Fruition Restaurant",
   "tags" : "American Food, Bars",
   "cost" : "$$$",
   "stars" : "4.32",
   "rank" : "17",
   "address" : "1313 E 6th Ave, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/UT4nGOhqYNEXYkWs-Cfpng/ls.jpg"
   },
   {
   "name" : "Sam's No. 3 Downtown",
   "tags" : "DIners, Mexican Restaurants, American (Traditional)",
   "cost" : "$$",
   "stars" : "1500 Curtis, St, Denverm CO",
   "rank" : "18",
   "address" : "1500 Curtis St, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/gkl12xujRvYQWk89v8njEg/ls.jpg"
   },
   {
   "name" : "Mercantile Dining & Provision",
   "tags" : "Bars, American Food",
   "cost" : "$$",
   "stars" : "4.37",
   "rank" : "19",
   "address" : "1701 Wynkoop St, Ste 155, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/La36RRv14CheGs4x5WAR2Q/ls.jpg"
   },
   {
   "name" : "Pho 95",
   "tags" : "Vietnamese Food, Vegetarian Restaurants, Soup",
   "cost" : "$$",
   "stars" : "4.64",
   "rank" : "20",
   "address" : "1401 S Federal Blvd, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/O5hkZMzIMTdf6P3w2Gw0Yg/ls.jpg"
   },
   {
   "name" : "True Food Kitchen",
   "tags" : "American Food, Vegetarian Restaurant, Vegan",
   "cost" : "$$",
   "stars" : "3.95",
   "rank" : "21",
   "address" : "2800 E 2nd Ave, Ste 101, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/4SH50wkUMjsNtdjz-b06Og/ls.jpg"
   },
   {
   "name" : "City O' City",
   "tags" : "Breakfast, Vegan, American (Traditional)",
   "cost" : "$$",
   "stars" : "4.31",
   "rank" : "22",
   "address" : "206 E 13th Ave, Denver, CO",
   "img" : "https://s3-media3.fl.yelpcdn.com/bphoto/wjE50PIHczYudxp-wMYLqQ/ls.jpg"
   },
   {
   "name" : "Acorn - Denver",
   "tags" : "American Food, Venues & Event Spaces",
   "cost" : "$$",
   "stars" : "4.64",
   "rank" : "23",
   "address" : "3350 Brighton Blvd, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/8CilLqqMUWeyIhmtubzcew/ls.jpg"
   },
   {
   "name" : "Sassafras American Eatery",
   "tags" : "Breakfast",
   "cost" : "$$",
   "stars" : "4.34",
   "rank" : "24",
   "address" : "320 East Colfax Ave, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/6ZELZgBs11K5t_Jih8qL0w/ls.jpg"
   },
   {
   "name" : "Panzano",
   "tags" : "Italian, Bars, Breakfast",
   "cost" : "$$$",
   "stars" : "4.39",
   "rank" : "25",
   "address" : "909 17th St, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/_MJ1MIzIddTYDfjKcdVAGg/ls.jpg"
   },
   {
   "name" : "Jelly Cafe",
   "tags" : "American Food, Breakfast, Sandwiches",
   "cost" : "$$",
   "stars" : "4.10",
   "rank" : "26",
   "address" : "600 E 13th Ave, Denver, CO",
   "img" : "https://s3-media1.fl.yelpcdn.com/bphoto/SguHsFMRWx8tTHpxZ32P_A/ls.jpg"
   },
   {
   "name" : "Vesta",
   "tags" : "American Food, Desserts, Wine",
   "cost" : "$$$",
   "stars" : "1822 Blake St, Denver, CO",
   "rank" : "27",
   "address" : "1822 Blake St, Denver, CO",
   "img" : "https://s3-media2.fl.yelpcdn.com/bphoto/LA6JeuX388_8VUwJZmIfcg/ls.jpg"
   },
   {
   "name" : "Odyssey Italian Restaurant",
   "tags" : "Italian",
   "cost" : "$$",
   "stars" : "4.52",
   "rank" : "28",
   "address" : "603 E 6th Ave, Denver, CO",
   "img" : "https://s3-media0.fl.yelpcdn.com/bphoto/Hv4-aBoXAinHa4-u3vBG5g/ls.jpg"
   },
   {
   "name" : "5280 Burger Bar",
   "tags" : "Burgers, American (Traditional)",
   "cost" : "$$",
   "stars" : "4.54",
   "rank" : "29",
   "address" : "500 16th St, Ste 160, Denver, CO",
   "img" : "https://s3-media3.fl.yelpcdn.com/bphoto/9VjVU7E-IFzdL7XwBWLHIw/ls.jpg"
   },
   {
   "name" : "Marco's Coal Fired",
   "tags" : "Pizza, Italian, Bars",
   "cost" : "$$",
   "stars" : "4.11",
   "rank" : "30",
   "address" : "2129 Larimer St, Denver, CO",
   "img" : "https://s3-media3.fl.yelpcdn.com/bphoto/GENJNpKXqteiMILxDNXmag/ls.jpg"
   },
   
 ]
 const foodCategories = 
   {
   "categories" : [ 
       "Afghan",
       "African",
       "American (Traditional)",
       "American Food",
       "Arabian",
       "Argentine",
       "Armenian",
       "Asian Fusion",
       "Australian",
       "Austrian",
       "Bangladeshi",
       "Basque",
       "BBQ",
       "Belgian",
       "Brasseries",
       "Brazilian",
       "Breakfast",
       "British",
       "Buffets",
       "Bulgarian",
       "Burgers",
       "Burmese",
       "Cafes",
       "Cafeteria",
       "Cajun Restaurants",
       "Calabrian",
       "Cambodian",
       "Cantonese",
       "Caribbean",
       "Catalan",
       "Cheesesteaks",
       "Chicken Shop",
       "Chinese Food",
       "Colombian",
       "Comfort Food",
       "Conveyor Belt Sushi",
       "Creperies",
       "Cuban",
       "Czech",
       "Delis",
       "Dim Sum",
       "Diners",
       "Dinner Theater",
       "Dominican",
       "Egyptian",
       "Eritrean",
       "Ethiopian",
       "Falafel",
       "Fast Food",
       "Filipino Food",
       "Fish & Chips",
       "Fondue",
       "Food Court",
       "Food Stands",
       "French Restaurants",
       "Game Meat",
       "Gastropubs",
       "Georgian",
       "German Food",
       "Gluten Free Restaurants",
       "Greek Food",
       "Guamanian",
       "Hainan",
       "Haitian",
       "Halal",
       "Hawaiian Food",
       "Himalayan/Nepalese",
       "Honduran",
       "Hong Kong Style Cafe",
       "Hot Dogs",
       "Hot Pot",
       "Hungarian",
       "Iberian",
       "Indian Restaurants",
       "Indonesian",
       "Irish",
       "Italian",
       "Izakaya",
       "Japanese Curry",
       "Japanese Food",
       "Kebab",
       "Korean Food",
       "Kosher",
       "Laotian",
       "Latin Restaurants",
       "Lebanese",
       "Live/Raw Food",
       "Malaysian",
       "Mauritius",
       "Mediterranean Food",
       "Mexican Restaurants",
       "Middle Eastern",
       "Modern European",
       "Mongolian",
       "Moroccan",
       "New Mexican Cuisine",
       "Nicaraguan",
       "Noodles",
       "Pakistani",
       "Pan Asian",
       "Pancakes",
       "Persian/Iranian",
       "Peruvian",
       "Pizza",
       "Polish",
       "Polynesian",
       "Pop-Up Restaurants",
       "Portuguese",
       "Poutineries",
       "Puerto Rican",
       "Ramen",
       "Reunion",
       "Russian",
       "Salads",
       "Salvadoran",
       "Sandwiches",
       "Sardinian",
       "Scandinavian",
       "Scottish",
       "Seafood",
       "Senegalese",
       "Sicilian",
       "Singaporean",
       "Slovakian",
       "Somali",
       "Soul Food", 
       "Soup",
       "Southern Food",
       "Spanish",
       "Sri Lankan",
       "Steak",
       "Supper Clubs",
       "Sushi",
       "Syrian",
       "Szechuan",
       "Tacos",
       "Taiwanese",
       "Tapas",
       "Tapas/Small Plates",
       "Teppanyaki",
       "Tex-Mex",
       "Thai",
       "Themed Cafes",
       "Trinidadian",
       "Turkish",
       "Tuscan",
       "Ukrainian",
       "Uzbek",
       "Vegan",
       "Vegetarian Restaurants",
       "Venezuelan",
       "Vietnamese Food",
       "Waffles",
       "Wings",
       "Wraps"
     ],
     "pricing" : [{"$": "0-10"},{"$$": "11-30"},{"$$$": "31-60"},{"$$$$": "61-2000"}]
   }
